apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: flink-processor
  namespace: kafka
  labels:
    strimzi.io/cluster: "iot"
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: raw-sensor-data
        operation: Read
      - resource:
          type: topic
          name: "sql-features"
        operation: Write
      - resource:
          type: topic
          name: "advanced-features"
        operation: Write
      - resource:
          type: topic
          name: "predictions"
        operation: Write
      - resource:
          type: topic
          name: "analysis"
        operation: Write
  quotas:
    producerByteRate: 2097152  # 2MB/s
    consumerByteRate: 2097152  # 2MB/s