apiVersion: v1
kind: ServiceAccount
metadata:
  name: health-api
  namespace: health-api
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: health-api
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: health-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: health-api
subjects:
- kind: ServiceAccount
  name: health-api
  namespace: health-api
