apiVersion: v1
kind: ConfigMap
metadata:
  name: flink-config
data:
  FLINK_PROPERTIES: |
    # Cluster settings
    jobmanager.rpc.address: flink-jobmanager
    taskmanager.numberOfTaskSlots: 4
    parallelism.default: 4
    
    # Checkpointing for fault tolerance
    execution.checkpointing.interval: 60000
    execution.checkpointing.mode: EXACTLY_ONCE
    execution.checkpointing.timeout: 600000
    state.backend: rocksdb
    state.backend.incremental: true
    state.checkpoints.dir: file:///flink-data/checkpoints
    state.savepoints.dir: file:///flink-data/savepoints
    
    # High availability
    high-availability.type: kubernetes
    high-availability.storageDir: file:///flink-data/ha
    kubernetes.cluster-id: sensor-analytics
    kubernetes.namespace: flink
    
    # Metrics
    metrics.reporters: prom
    metrics.reporter.prom.class: org.apache.flink.metrics.prometheus.PrometheusReporter
    metrics.reporter.prom.port: 9249
    
    # Python settings
    python.client.executable: python3
    python.executable: python3