apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-jobmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink
      component: jobmanager
  template:
    metadata:
      labels:
        app: flink
        component: jobmanager
    spec:
      serviceAccountName: flink
      containers:
      - name: jobmanager
        image: localhost:5000/flink-python:latest
        args: ["jobmanager"]
        ports:
        - containerPort: 6123
          name: rpc
        - containerPort: 8081
          name: ui
        - containerPort: 9249
          name: metrics
        envFrom:
        - configMapRef:
            name: flink-config
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "iot-kafka-brokers.kafka.svc.cluster.local:9092"
        - name: JOB_MANAGER_RPC_ADDRESS
          value: "flink-jobmanager"
        volumeMounts:
        - name: flink-data
          mountPath: /flink-data
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          tcpSocket:
            port: 6123
          initialDelaySeconds: 30
          periodSeconds: 60
        readinessProbe:
          tcpSocket:
            port: 6123
          initialDelaySeconds: 30
          periodSeconds: 60
      volumes:
      - name: flink-data
        persistentVolumeClaim:
          claimName: flink-data
