apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-taskmanager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flink
      component: taskmanager
  template:
    metadata:
      labels:
        app: flink
        component: taskmanager
    spec:
      serviceAccountName: flink
      containers:
      - name: taskmanager
        image: localhost:5000/flink-python:latest
        args: ["taskmanager"]
        ports:
        - containerPort: 9249
          name: metrics
        envFrom:
        - configMapRef:
            name: flink-config
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "iot-kafka-brokers.kafka.svc.cluster.local:9092"
        volumeMounts:
        - name: flink-data
          mountPath: /flink-data
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          tcpSocket:
            port: 6122
          initialDelaySeconds: 30
          periodSeconds: 60
      volumes:
      - name: flink-data
        persistentVolumeClaim:
          claimName: flink-data
