apiVersion: v1
kind: Service
metadata:
  name: flink-metrics
  namespace: flink
  labels:
    app: flink
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9249"
spec:
  ports:
    - name: metrics
      port: 9249
      targetPort: 9249
  selector:
    app: flink
  type: ClusterIP