apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: raw-sensor-data
  namespace: kafka
  labels:
    strimzi.io/cluster: "iot"
spec:
  partitions: 6  # Reduced for local development
  replicas: 3
  config:
    retention.ms: 604800000  # 7 days
    cleanup.policy: delete
    min.insync.replicas: 2
    max.message.bytes: 5242880