apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: sql-features
  namespace: kafka
  labels:
    strimzi.io/cluster: "iot"
spec:
  partitions: 6  # Reduced for local development
  replicas: 3
  config:
    min.insync.replicas: 2
    max.message.bytes: 5242880
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: advanced-features
  namespace: kafka
  labels:
    strimzi.io/cluster: "iot"
spec:
  partitions: 6  # Reduced for local development
  replicas: 3
  config:
    min.insync.replicas: 2
    max.message.bytes: 5242880
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: predictions
  namespace: kafka
  labels:
    strimzi.io/cluster: "iot"
spec:
  partitions: 3  # Reduced for local development
  replicas: 3
  config:
    min.insync.replicas: 2
    max.message.bytes: 5242880
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: analysis
  namespace: kafka
  labels:
    strimzi.io/cluster: "iot"
spec:
  partitions: 3  # Reduced for local development
  replicas: 3
  config:
    min.insync.replicas: 2
    max.message.bytes: 5242880